Repository bongtubaekseo/BongBaek-iOS, pull requests merged in 2025-07, with the labels that each got.

#14 Feat/#6 home view
  BongBaek/BongBaek.xcodeproj/project.pbxproj
  BongBaek/BongBaek.xcodeproj/xcshareddata/xcschemes/BongBaek.xcscheme
  BongBaek/BongBaek/Application/BongBaekApp.swift
  BongBaek/BongBaek/BongBaek.entitlements
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Colors/background/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Colors/background/background.colorset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Colors/button_back.colorset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_alarm.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_alarm.imageset/icon_alarm.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_calendar.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_calendar.imageset/icon_calendar.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_card.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_card.imageset/icon_card.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_clock.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_clock.imageset/icon_clock.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_location.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_location.imageset/icon_location.png
  BongBaek/BongBaek/Presentation/Home/FullSchedule/FullScheduleView.swift
  BongBaek/BongBaek/Presentation/Home/Recommends/RecommendsView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmCellView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleCellView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleModel.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleView.swift
  BongBaek/BongBaek/Presentation/Home/View/HomeView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendView.swift
Labels: 강현우, Feat

#20 Feat/#19 Recommend Loading View
  BongBaek/BongBaek.xcodeproj/project.pbxproj
  BongBaek/BongBaek.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  BongBaek/BongBaek/Application/BongBaekApp.swift
  BongBaek/BongBaek/Presentation/Recommend/Test/LoadingView.swift
  BongBaek/BongBaek/Presentation/Recommend/Test/LottieTest.swift
  BongBaek/BongBaek/Presentation/Recommend/Test/envelope.json
  BongBaek/BongBaek/Presentation/Recommend/Test/find_amount.json
  BongBaek/BongBaek/Presentation/Recommend/Test/success.json
  BongBaek/BongBaek/Presentation/Recommend/View/Lottie/Lottie.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLoadingView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendSuccessView.swift
Labels: 강현우, Feat

#24 [feat] 최종 추천 금액 UI 일부 구현 작업(lottie 제외)
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_colorcheck.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_colorcheck.imageset/icon_colorcheck.svg
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_info.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_info.imageset/icon_info.svg
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_location 2.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_location 2.imageset/icon_location.svg
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_star.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_star.imageset/icon_star.svg
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendCostView.swift
  BongBaek/BongBaek/Presentation/Recommend/ViewModel/RecommendCostViewModel.swift
Labels: 김현우, Feat

#26 Feat/#21 Recommend Lottie UI
  BongBaek/BongBaek/Application/BongBaekApp.swift
  BongBaek/BongBaek/Global/Extensions/Font+.swift
  BongBaek/BongBaek/Presentation/Recommend/View/Lottie/LottieView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendCostView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLottie.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendSuccessView.swift
Labels: 강현우, Feat

#31 Settings/#2 network
  BongBaek/BongBaek.xcodeproj/project.pbxproj
  BongBaek/BongBaek/Application/BongBaekApp.swift
  BongBaek/BongBaek/Info.plist
  BongBaek/BongBaek/Network/Base/AppConfig.swift
  BongBaek/BongBaek/Network/Base/AuthTarget.swift
  BongBaek/BongBaek/Network/Base/DIContainer.swift
  BongBaek/BongBaek/Network/Base/EventsTarget.swift
  BongBaek/BongBaek/Network/Model/Request/AmountRecommendationRequest.swift
  BongBaek/BongBaek/Network/Model/Request/CreateEventData.swift
  BongBaek/BongBaek/Network/Model/Request/MemberInfo.swift
  BongBaek/BongBaek/Network/Model/Response/BaseResponse.swift
  BongBaek/BongBaek/Network/Model/Response/EventHomeResponse.swift
  BongBaek/BongBaek/Network/Model/Response/SignUpResponseData.swift
  BongBaek/BongBaek/Network/Protocols/AuthServiceProtocol.swift
  BongBaek/BongBaek/Network/Protocols/EventServicceeProtocol.swift
  BongBaek/BongBaek/Network/Protocols/NetworkServiceProtocol.swift
  BongBaek/BongBaek/Network/Services/AuthService.swift
  BongBaek/BongBaek/Network/Services/EventService.swift
  BongBaek/BongBaek/Network/Services/NetworkService.swift
  BongBaek/BongBaek/Presentation/Home/ViewModel/EventViewModel.swift
  BongBaek/BongBaek/Presentation/Login/ViewModel/AuthViewModel.swift
Labels: 임재현, Feat, Setting

#37 Feat/#32 navigation path
  BongBaek/BongBaek/Application/BongBaekApp.swift
  BongBaek/BongBaek/Global/AppStateManager.swift
  BongBaek/BongBaek/Global/Components/CheckButton.swift
  BongBaek/BongBaek/Global/Components/TextField/CustomTextField.swift
  BongBaek/BongBaek/Global/Extensions/Colors+.swift
  BongBaek/BongBaek/Global/NavigationPathManager.swift
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Frame 2087329064.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Frame 2087329064.imageset/Frame 2087329064.svg
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/btn_kakao.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/btn_kakao.imageset/btn_kakao.svg
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/onboarding_ios.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/onboarding_ios.imageset/onboarding_ios3.png
  BongBaek/BongBaek/Presentation/Home/MainTabView.swift
  BongBaek/BongBaek/Presentation/Home/Recommends/RecommendsView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleModel.swift
  BongBaek/BongBaek/Presentation/Home/View/HomeView.swift
  BongBaek/BongBaek/Presentation/Login/View/DatePickerBottomSheetView.swift
  BongBaek/BongBaek/Presentation/Login/View/LaunchView.swift
  BongBaek/BongBaek/Presentation/Login/View/LoginView.swift
  BongBaek/BongBaek/Presentation/Login/View/ProfileSettingView.swift
  BongBaek/BongBaek/Presentation/Login/View/RootView.swift
  BongBaek/BongBaek/Presentation/Login/View/SignUpBottomSheetView.swift
  BongBaek/BongBaek/Presentation/Login/View/WelcomeTextView.swift
  BongBaek/BongBaek/Presentation/Login/ViewModel/AuthViewModel.swift
  BongBaek/BongBaek/Presentation/Login/ViewModel/LoginViewModel.swift
  BongBaek/BongBaek/Presentation/Recommend/Test/success.json
  BongBaek/BongBaek/Presentation/Recommend/View/EventDateView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/EventInformationView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/EventLocationView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/ModifyEventView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendCostView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLoadingView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLottie.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendStartView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendSuccessView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendView.swift
Labels: 임재현, Feat, Fix

#38 Feat/#33 kakao login
  BongBaek/BongBaek.xcodeproj/project.pbxproj
  BongBaek/BongBaek.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  BongBaek/BongBaek/Application/BongBaekApp.swift
  BongBaek/BongBaek/Info.plist
  BongBaek/BongBaek/Presentation/Login/View/LoginView.swift
  BongBaek/BongBaek/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: 강현우, Feat

#39 Fix/#36 RecommendCostView
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendCostView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLottie.swift
Labels: 강현우, Feat

#46 [feat] ScheduleModel 별로 View 클릭 시 각각의 AllRecords로 넘어가는 플로우 구현
  BongBaek/BongBaek/Presentation/Home/Empty/EmptyCardView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleModel.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleView.swift
  BongBaek/BongBaek/Presentation/Record/View/AllRecordsView.swift
Labels: 김현우, Feat

#47 Feat/#42 Records Filtering
  BongBaek/BongBaek/Presentation/Home/FullSchedule/FullScheduleView.swift
Labels: 강현우, Feat

#49 Feat/#48 Empty Record View
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmView.swift
  BongBaek/BongBaek/Presentation/Home/View/HomeView.swift
  BongBaek/BongBaek/Presentation/Record/View/RecordView.swift
Labels: 강현우, Feat

#51 Fix#50 Detail
  BongBaek/BongBaek/Presentation/Home/FullSchedule/FullScheduleView.swift
  BongBaek/BongBaek/Presentation/Record/View/RecordView.swift
Labels: 강현우, Feat, Fix

#55 Feat/#53 Record api
  BongBaek/BongBaek/Global/NavigationPathManager.swift
  BongBaek/BongBaek/Network/Base/EventsTarget.swift
  BongBaek/BongBaek/Network/Model/Response/EventHomeResponse.swift
  BongBaek/BongBaek/Network/Protocols/EventServicceeProtocol.swift
  BongBaek/BongBaek/Network/Services/EventService.swift
  BongBaek/BongBaek/Presentation/Home/MainTabView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmCellView.swift
  BongBaek/BongBaek/Presentation/Home/ViewModel/EventViewModel.swift
  BongBaek/BongBaek/Presentation/Recommend/View/ModifyEventView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendCostView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLottie.swift
  BongBaek/BongBaek/Presentation/Record/View/AllRecordsView.swift
  BongBaek/BongBaek/Presentation/Record/View/RecordView.swift
  BongBaek/BongBaek/Presentation/Record/ViewModel/AllRecordsViewmodel.swift
  BongBaek/BongBaek/Presentation/Record/ViewModel/RecordViewModel.swift
Labels: 임재현, Feat

#62 Fix/#61 QA home
  BongBaek/BongBaek/Presentation/Home/Empty/EmptyCardView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmCellView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmView.swift
Labels: 강현우, Feat, Fix

#70 Fix/#69 QA_2
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLoadingView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLottie.swift
  BongBaek/BongBaek/Presentation/Recommend/ViewModel/RecommendCostViewModel.swift
Labels: 강현우, Fix
