Repository bongtubaekseo/BongBaek-iOS, pull requests merged in 2025-09, with the labels that each got.

#91 [Faet] 마이페이지 View 구현
  BongBaek/BongBaek/Global/NavigationPathManager.swift
  BongBaek/BongBaek/Presentation/Home/MainTabView.swift
  BongBaek/BongBaek/Presentation/Home/View/HomeView.swift
  BongBaek/BongBaek/Presentation/MyPage/View/ModifyView.swift
  BongBaek/BongBaek/Presentation/MyPage/View/MyPageView.swift
Labels: 강현우, Feat

#92 [FEAT] 기록하기 화면 UI 수정 작업
  BongBaek/BongBaek/Presentation/Home/FullSchedule/FullScheduleView.swift
  BongBaek/BongBaek/Presentation/Record/View/RecordView.swift
  BongBaek/BongBaek/Presentation/Record/ViewModel/RecordViewModel.swift
Labels: 임재현, Fix

#97 [Feat] MyPage API 세팅 구현
  BongBaek/BongBaek/Network/Base/MyPageTarget.swift
  BongBaek/BongBaek/Network/Model/Request/MyPageData.swift
Labels: 강현우, Feat, Setting

#114 [Fix] 1차 QA 추가 수정사항 반영
  BongBaek/BongBaek/Global/Extensions/Font+.swift
  BongBaek/BongBaek/Presentation/AccountDeletionView.swift
  BongBaek/BongBaek/Presentation/Home/FullSchedule/FullScheduleView.swift
Labels: 강현우, Fix

#117 [Fix] FullScheduleView 수정사항
  BongBaek/BongBaek/Presentation/Home/FullSchedule/FullScheduleView.swift
Labels: 강현우, Chore, Fix

#121 [Fix] 디자인 QA 반영
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/home_logo.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/home_logo.imageset/home_logo.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/home_logo.imageset/home_logo1x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/home_logo.imageset/home_logo2x.png
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmCellView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleCellView.swift
  BongBaek/BongBaek/Presentation/Home/View/HomeView.swift
Labels: 강현우, Fix

#120 [Fix] 디자인 QA 수정사항 반영
  BongBaek/BongBaek.xcodeproj/project.pbxproj
  BongBaek/BongBaek/Global/Components/TabView/CustomTabView.swift
  BongBaek/BongBaek/Global/EventCreationManager.swift
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Knob 1.imageset/Knob.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Knob 1.imageset/Knob@2x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Knob 1.imageset/Knob@3x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Knob.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Knob.imageset/Knob.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Knob.imageset/Knob.svg
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Knob.imageset/Knob@2x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/Knob.imageset/Knob@3x.png
  BongBaek/BongBaek/Network/Base/AppConfig.swift
  BongBaek/BongBaek/Presentation/CreateEventView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/ModifyEventView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendFlow/EventDateView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendFlow/EventInformationView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendFlow/RecommendView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLottie.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RelationshipSliderView.swift
Labels: 임재현, Fix

#123 [Fix] QA 중간 반영 업데이트
  BongBaek/BongBaek/Presentation/Home/FullSchedule/FullScheduleView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleAlarmView.swift
  BongBaek/BongBaek/Presentation/MyPage/View/MyPageView.swift
  BongBaek/BongBaek/Presentation/Record/View/AllRecordsView.swift
  BongBaek/BongBaek/Presentation/Record/View/RecordView.swift
  BongBaek/BongBaek/Presentation/Record/ViewModel/RecordViewModel.swift
Labels: 강현우, Fix

#124 [Feat] QA 수정안 반영
  BongBaek/BongBaek.xcodeproj/project.pbxproj
  BongBaek/BongBaek/Global/Components/CustomDropDownView.swift
  BongBaek/BongBaek/Global/Components/TextField/BorderStyleTextField.swift
  BongBaek/BongBaek/Global/Components/TextField/CustomTextField.swift
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/checkbox 1.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/checkbox 1.imageset/checkbox.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/checkbox 1.imageset/checkbox@2x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/checkbox 1.imageset/checkbox@3x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/checkbox.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/checkbox.imageset/checkbox.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/checkbox.imageset/checkbox@2x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/checkbox.imageset/checkbox@3x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_check 3.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_check 3.imageset/icon_check.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_check 3.imageset/icon_check@2x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_check 3.imageset/icon_check@3x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_location 6.imageset/Contents.json
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_location 6.imageset/icon_location.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_location 6.imageset/icon_location@2x.png
  BongBaek/BongBaek/Global/Resources/Assets.xcassets/Icons/icon_location 6.imageset/icon_location@3x.png
  BongBaek/BongBaek/Presentation/AccountDeletionView.swift
  BongBaek/BongBaek/Presentation/CreateEventView.swift
  BongBaek/BongBaek/Presentation/Home/FullSchedule/FullScheduleView.swift
  BongBaek/BongBaek/Presentation/Home/Schedule/ScheduleView.swift
  BongBaek/BongBaek/Presentation/Home/View/HomeView.swift
  BongBaek/BongBaek/Presentation/Login/View/ProfileSettingView.swift
  BongBaek/BongBaek/Presentation/MyPage/View/ModifyView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/DetailRecommendButton.swift
  BongBaek/BongBaek/Presentation/Recommend/View/ModifyEventView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendFlow/EventDateView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendFlow/EventInformationView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendFlow/EventLocationView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendFlow/LargeMapView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendFlow/RecommendView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendGuideTextView.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RecommendLottie.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RelationshipButton.swift
  BongBaek/BongBaek/Presentation/Recommend/View/RelationshipSliderView.swift
  BongBaek/BongBaek/Presentation/Record/View/AllRecordsView.swift
Labels: Fix
